### ISSUE TITLE
BrainBox refuses to receive requests from foodbox

### ISSUE THREAD

**Issue by michaeldub** [FatCatProject/BrainBox#27]
#4 
![15](https://user-images.githubusercontent.com/26785556/30825084-6e52b03c-a23a-11e7-9ced-256079fea617.png)

**Comment by michaeldub** [comment]
raspberry connected to pc via cable
Firewall is off
telnet to same ip:port, confirmed same issue.

**Comment by SheyDenis** [comment]
Fixed.
