### ISSUE TITLE
Create Models For DB

### ISSUE THREAD

**Issue by Shabnata** [FatCatProject/BrainBox#3]

**Comment by Shabnata** [comment]
to create db from models:
step1: stop the server from pyCharm (if running)
step2: got to project directory and delete the folder "migrations" if you have it
step3: delete the database file that you already have
step4 : in terminal run 2 commands:
python manage.py makemigrations bbox
python manage.py migrate
step5: check if you have all the needed tables

**Comment by michaeldub** [comment]
Tested
![db.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5981cb63db8151001f93c916/125516c66e82c728ace21e0d46ec96d86fc093bb80e3ba40b01faad67c1f25257105fa2f25d5b17eee132b51590d4ba9155a5646eee59b69f7e8682fd70541b8937f5566c73a1badbd821ab700b8248f4b86b1ba9801.png)
