### ISSUE TITLE
Add ability to announce presence on the network (Network discovery)

### ISSUE THREAD

**Issue by SheyDenis** [FatCatProject/BrainBox#5]
Allow a FoodBox to discover BrainBox on the network.

**Comment by SheyDenis** [comment]
Should work now, even if you run the BrainBox locally and FoodBox on a Pi.

**Comment by SheyDenis** [comment]
Doesn't actually works.
Need to figure out how to cause the server to run this code on startup.
The code it self works fine to publish a service, but not to remove it when the server goes down in a controlled manner.

**Comment by SheyDenis** [comment]
Ok now it should work fine.

**Comment by SheyDenis** [comment]
Everything works fine except a TypeError when shutting down the server while running on Windows.

**Comment by Shabnata** [comment]
Screenshot of an error:

![err1.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58fc829d563295002036c784/125516c66e82c728ace21e0d46ed868872c0cfeb9ffbb049a15ee4d67304722a2b52fb2a2981b678ed142a505f5f48fe445d0b46f5fb9b37b4f46d2ede0356b49b381d66cc2f10abb2831abf04b222884783b7b88d4bd2a5.jpg)
